// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKAKsH-WA-B-obJFNQwdweJTOhydONIZA',
    appId: '1:801394396965:web:c01786af84063af0ae14cc',
    messagingSenderId: '801394396965',
    projectId: 'danny-zoom',
    authDomain: 'danny-zoom.firebaseapp.com',
    storageBucket: 'danny-zoom.appspot.com',
    measurementId: 'G-QLH88JPCNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQqObkiaeuS94f5HtxAKDAUkcWrjxPAyg',
    appId: '1:801394396965:android:7669dc6ebdd18481ae14cc',
    messagingSenderId: '801394396965',
    projectId: 'danny-zoom',
    storageBucket: 'danny-zoom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVM_JCe1-_RBKKIFAwedpqd0OHwe0exSQ',
    appId: '1:801394396965:ios:5159e06a6e529242ae14cc',
    messagingSenderId: '801394396965',
    projectId: 'danny-zoom',
    storageBucket: 'danny-zoom.appspot.com',
    iosBundleId: 'com.example.dannyZoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVM_JCe1-_RBKKIFAwedpqd0OHwe0exSQ',
    appId: '1:801394396965:ios:5159e06a6e529242ae14cc',
    messagingSenderId: '801394396965',
    projectId: 'danny-zoom',
    storageBucket: 'danny-zoom.appspot.com',
    iosBundleId: 'com.example.dannyZoom',
  );
}
